<style>
* { box-sizing: border-box; } body {margin: 0;}*{box-sizing:border-box;}body{margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;}
</style>
<body><div class="threep"><div class="container text-center my-5"><!-- Logo --><img src="/storage/images/3-piece/Letter-A-Logo-With-Business-and-Arrow-Concept.-128-x-128-px-128-x-128-px3-2048x2048.png" alt="Logo" class="logo mb-3"/><h2 class="fw-bold text-magenta mb-4">সম্পূর্ণ অফসান প্রিন্ট করা আনস্টিচড 4 piece</h2><div class="row justify-content-center"><div class="col-md-5 mb-4"><div id="carouselOne" data-bs-ride="carousel" class="carousel slide"><div class="carousel-inner"><div class="carousel-item active"><img src="/storage/images/3-piece/3pcs-2.webp" alt="Item 1" class="d-block w-100 rounded"/></div><div class="carousel-item"><img src="/storage/images/3-piece/3pcs-4.webp" alt="Item 2" class="d-block w-100 rounded"/></div></div><button type="button" data-bs-target="#carouselOne" data-bs-slide="prev" class="carousel-control-prev"><span class="carousel-control-prev-icon"></span></button><button type="button" data-bs-target="#carouselOne" data-bs-slide="next" class="carousel-control-next"><span class="carousel-control-next-icon"></span></button></div></div><div class="col-md-5 mb-4"><div id="carouselTwo" data-bs-ride="carousel" class="carousel slide"><div class="carousel-inner"><div class="carousel-item active"><img src="/storage/images/3-piece/3pcs-4.webp" alt="Item 3" class="d-block w-100 rounded"/></div><div class="carousel-item"><img src="/storage/images/3-piece/3pcs-2.webp" alt="Item 4" class="d-block w-100 rounded"/></div></div><button type="button" data-bs-target="#carouselTwo" data-bs-slide="prev" class="carousel-control-prev"><span class="carousel-control-prev-icon"></span></button><button type="button" data-bs-target="#carouselTwo" data-bs-slide="next" class="carousel-control-next"><span class="carousel-control-next-icon"></span></button></div></div></div><p class="mt-3 fw-bold">
      বাজারের ক্রপি থ্রি পিসের সাথে আমাদের প্রোডাক্ট কে তুলনা করবেন না। আমরা নিজের তত্ত্বাবধানে ইসলামপুরে আমাদের নিজস্ব ফ্যাক্টরিতে মেশিনচালিত করে থাকি। কারণ আমরা সম্পূর্ণ কাপড় নিজেরাই তৈরি করি।
    </p><p class="fw-bold">কাপড়ের ওড়না ও থ্রিপিসের কাপড় সম্পূর্ণ যুক্ত কাপড়।</p><p class="fs-4 fw-bold">
      আজকের অফার মূল্য <span class="text-success">১১০০/=</span> <span class="text-danger">টাকা</span></p><a href="#" class="btn btn-pink px-4 py-2 fw-bold">✅ অর্ডার করতে চাই</a></div><section class="feature-section py-5"><div class="container"><div class="row align-items-center justify-content-center"><!-- Text Section --><div class="col-lg-6 mb-4 mb-lg-0"><h2 class="text-magenta fw-bold mb-4">আনস্টিচড ৩ পিস এর বৈশিষ্ট্য</h2><ul class="list-unstyled feature-list"><li><span class="tick">✔</span> জামা লং ৪৮ বডি ৫০+</li><li><span class="tick">✔</span> পায়জামা কাপড় দেওয়া ২.৫ গজ (৯০ ইঞ্চি)</li><li><span class="tick">✔</span> ওড়নার কাপড় দেওয়া আছে ৫.৫ হাতা</li><li><span class="tick">✔</span> সম্পূর্ণ অফসান প্রিন্ট করা</li><li><span class="tick">✔</span> ফেব্রিকা কটন সুতি</li></ul><a href="#" class="btn btn-order fw-bold mt-3">
            🛒 অর্ডার করতে চাই
          </a></div><!-- Image Carousel --><div class="col-lg-6"><div id="carouselProduct" data-bs-ride="carousel" class="carousel slide"><div class="carousel-inner"><div class="carousel-item active"><img src="/storage/images/3-piece/3pcs-3.webp" alt="Product 1" class="d-block w-100 rounded"/></div><div class="carousel-item"><img src="/storage/images/3-piece/3pcs-6.webp" alt="Product 2" class="d-block w-100 rounded"/></div></div><button type="button" data-bs-target="#carouselProduct" data-bs-slide="prev" class="carousel-control-prev"><span class="carousel-control-prev-icon"></span></button><button type="button" data-bs-target="#carouselProduct" data-bs-slide="next" class="carousel-control-next"><span class="carousel-control-next-icon"></span></button></div></div></div></div></section><section class="text-center py-5 bg-white"><div class="container"><h2 class="fw-bold text-danger mb-4">
        আমাদের মেসেঞ্জারে 24 ঘন্টার প্রতিনিয়ত একজন প্রতিনিধি একটিভ থাকে কোনো সমস্যা হলে সাথে সাথে মেসেঞ্জারে মেসেজ করবেন।
      </h2><div class="d-flex justify-content-center gap-3 flex-wrap"><a href="#" class="btn btn-facebook fw-bold px-5 py-4">ফেইসবুক</a><a href="#" class="btn btn-whatsapp fw-bold px-5 py-4">হোয়াটসঅ্যাপ</a></div></div></section><!-- Features Section --><section class="feature-section py-5"><div class="container"><h3 class="text-center fw-bold text-magenta mb-4">আনস্টিচড ৩ পিস এর বৈশিষ্ট্য</h3><div class="row justify-content-center"><div class="col-lg-8"><ul class="list-unstyled feature-list"><li><span class="tick">✔</span> আমরা নিজের তত্ত্বাবধানে ইসলামপুরে আমাদের নিজস্ব ফ্যাক্টরিতে মেশিনচালিত করে থাকি</li><li><span class="tick">✔</span> কারণ আমরা সম্পূর্ণ কাপড় নিজেরা প্রস্তুত করি কাপড়ের ওড়না ও পায়জামার কাপড় সম্পূর্ণ সুতি কাপড়।</li><li><span class="tick">✔</span> আর আমাদের মোবাইল নম্বারে সকাল দশটা হতে রাত দশটা পর্যন্ত পাওয়া যাবে।</li><li><span class="tick">✔</span> যদি প্রোডাক্টের কোন সমস্যা থাকে উক্ত প্রোডাক্টের একটি ভিডিও অথবা মেসেঞ্জার অথবা হোয়াটসঅ্যাপে ভিডিও দিবেন।</li><li><span class="tick">✔</span> যদি আমাদের সমস্যা যুক্তিসঙ্গত মনে করি তাহলে আমরা বিনা ডেলিভারি চার্জে প্রোডাক্ট এক্সচেঞ্জ করে দিব।</li></ul><div class="text-center mt-4"><a href="#" class="btn btn-order fw-bold">🛒 অর্ডার করতে চাই</a></div></div></div></div></section></div></body>
