<style>
* { box-sizing: border-box; } body {margin: 0;}*{box-sizing:border-box;}body{margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;}.container.text-center.my-5{width:70px;}
</style>
<body><div class="allergycure"><!-- Hero Section --><section class="hero-section d-flex align-items-center"><div class="container"><div class="row align-items-center"><!-- Left Text --><div class="col-lg-7 text-center text-lg-start mb-4 mb-lg-0"><img src="/storage/images//allergy-cure/Brand-Logo-2.png" alt="Brand Logo" class="mb-3 brand-logo"/><h2 class="hero-heading">
            প্রাকৃতিকভাবে এলার্জি থেকে মুক্তি নিন আমাদের এলার্জি নিদ্রাশন এবং চর্মরোগ অয়েল ব্যবহারের মাধ্যমে<br/>
            এলার্জি দিন শেষ প্রকৃতি বাংলাদেশ
          </h2><a href="#" class="btn btn-warning btn-lg mt-4 fw-bold">অর্ডার করু এখন</a></div><!-- Right Video --><div class="col-lg-5 text-center"><div class="ratio ratio-4x3 video-frame"><iframe allowfullscreen="" src="https://www.youtube.com/embed/YOUR_VIDEO_ID?" title="YouTube video"></iframe></div></div></div></div></section><!-- Offer Section --><section class="offer-section text-center py-5 bg-light"><div class="container"><h4 class="text-course">১ মাসের কোর্স</h4><p class="line-through"><span class="text-decoration-line-through">১ ফাইল রেগুলার মূল্য ১১৫০ টাকা</span></p><p class="offer-price">
        বর্তমান অফার মূল্য <span class="offer-amount">৯৫০ টাকা</span></p><p class="delivery-note">ডেলিভারি চার্জ ফ্রি</p></div></section><!-- Call Button --><section class="offer-extended text-center py-5 bg-light"><div class="container"><img src="/storage/images/allergy-cure/3-2-1024x1024.jpg" alt="Chormorog Tel" class="img-fluid mb-4 offer-image"/><p class="offer-description mx-auto mb-4">
        আমাদের এলার্জি নিকাশন এবং চর্মরোগ অয়েল, ১ এক ফাইল ১ মাস ব্যবহার করলেই,<br/>
        আপনি পুরুষপুচরি ভাবে সুস্থ হয়ে যাবেন ইনশাআল্লাহ, ১ ফাইল ১১৫০ টাকা, আজকের জন্য<br/>
        অফার প্রাইস ৯৫০ টাকা সাথে সারা বাংলাদেশ ডেলিভারি চার্জ ফ্রি
      </p><a href="#" class="btn btn-order">অর্ডার করুন 🛒</a></div></section><!-- Reviews Heading --><section class="review-section bg-light text-center py-5"><div class="container"><h2 class="review-title mb-5">কাস্টমার রিভিউ</h2><div class="row g-4 justify-content-center"><div class="col-md-6 col-lg-3"><img src="/storage/images/allergy-cure/r-2.jpg" alt="Customer Chat 1" class="img-fluid rounded shadow-sm"/></div><div class="col-md-6 col-lg-3"><img src="/storage/images/allergy-cure/r-4-1.jpg" alt="Customer Chat 2" class="img-fluid rounded shadow-sm"/></div><div class="col-md-6 col-lg-3"><img src="/storage/images/allergy-cure/r-6-1.jpg" alt="Customer Chat 3" class="img-fluid rounded shadow-sm"/></div><div class="col-md-6 col-lg-3"><img src="/storage/images/allergy-cure/r-7-1.jpg" alt="Customer Chat 4" class="img-fluid rounded shadow-sm"/></div></div></div></section><section class="offer-extended text-center py-5 bg-light"><div class="container"><img src="/storage/images/allergy-cure/4-2-1024x1024 (1).jpg" alt="Chormorog Tel" class="img-fluid mb-4 offer-image"/></div></section><section class="text-center py-3"><div class="greenbox text-center"><p class="offer-description1 mx-auto mb-5">
        রোগ বিবরণ : ইহা সাধারণত ছোঁয়াচে রোগ। ফোস্কুরির মত পুঁজ যুক্ত, রস যুক্ত, শুষ্ক বিভিন্ন প্রকার চর্ম রোগ দেখা যায়। 
        ইহা অতিরিক্ত কষ্ট দায়ক রোগ। সহজে আরোগ্য হইতে চাই না, ইহাতে রক্ত দূষিত হয়ে পড়ে। অপরিষ্কার অপরিচ্ছন্ন তার 
        কারণে এই রোগ বেশি হয়। তাই আপনার জন্য নিয়ে এসেছি এলার্জি নিষ্কাশন এবং চমরোগ ওয়েল,,, এটা ব্যবহারে আপনাদের 
        ১০০ বছরের পুরাতন এলার্জি সহ যাবতীয় চর্মরোগ দাউদ একজিমা খুসা পাঁচরা বিনাশ করবে ইনশাআল্লাহ।
      </p></div></section><div class="text-center"><button class="btn-order">অর্ডার করতে চাই</button></div><section class="text-center py-3"><div class="greenbox text-center"><p class="offer-description1 mx-auto">
    এলার্জি নিষ্কাশন উপকারিতাঃ
  </p></div></section><section class="offer-extended text-center py-5 bg-light"><div class="container"><img src="/storage/images/allergy-cure/3-2-1024x1024.jpg" alt="Chormorog Tel" class="img-fluid mb-4 offer-image"/></div></section><section class="bg-light py-5 text-center"><div class="container"><div class="row text-start justify-content-center"><div class="col-md-6"><ul class="benefit-list"><li><i class="bi bi-check-circle-fill"></i> ১০০ বছরের পুরাতন এলার্জি দূর করবে</li><li><i class="bi bi-check-circle-fill"></i> দুই রানের মাঝের চুলকানি দূর করবে</li><li><i class="bi bi-check-circle-fill"></i> চোখে চুলকানি দূর করবে</li><li><i class="bi bi-check-circle-fill"></i> এলার্জির সমস্যা চিরতরে দূর করে</li><li><i class="bi bi-check-circle-fill"></i> রক্ত পরিশুদ্ধ করবে</li><li><i class="bi bi-check-circle-fill"></i> কুমিনাশক দূর করবে</li><li><i class="bi bi-check-circle-fill"></i> ছত্রাকের ইনফেকশন দূর করতে</li><li><i class="bi bi-check-circle-fill"></i> চুলকানি চিরতরে দূর করবে</li></ul></div><div class="col-md-6"><ul class="benefit-list"><li><i class="bi bi-check-circle-fill"></i> বিভিন্ন অঙ্গে চুলকানি সহ যাবতীয়</li><li><i class="bi bi-check-circle-fill"></i> এলার্জির জণিত সমস্যা দূর করবে</li><li><i class="bi bi-check-circle-fill"></i> জীবাণুনাশক অ্যান্টিসেপটিক দূর করবে</li><li><i class="bi bi-check-circle-fill"></i> চুলকানি, কোলেস্টেরল, দামন করবে</li><li><i class="bi bi-check-circle-fill"></i> রক্ত এলার্জি দূর করবে</li><li><i class="bi bi-check-circle-fill"></i> জ্বালাপোড়া ভাব দূর করবে</li><li><i class="bi bi-check-circle-fill"></i> ব্লাড সুগার নিয়ন্ত্রণ করবে</li><li><i class="bi bi-check-circle-fill"></i> মাথায় গোঁটা এলার্জি দূর করবে</li><li><i class="bi bi-check-circle-fill"></i> মুখ মেছতা বা ফুলা ভাব দূর করবে</li></ul></div></div></div></section><div class="text-center"><button class="btn-order">অর্ডার করুন 🛒</button></div><section class="text-center py-3"><div class="greenbox text-center"><p class="offer-description1 mx-auto">
    চর্মরোগ অয়েলের উপকারীতাঃ
  </p></div></section><section class="offer-extended text-center py-5 bg-light"><div class="container"><img src="/storage/images/allergy-cure/3-2-1024x1024.jpg" alt="Chormorog Tel" class="img-fluid mb-4 offer-image"/></div></section><section class="bg-light py-5 text-center"><div class="container"><div class="row text-start justify-content-center"><div class="col-md-6"><ul class="benefit-list"><li><i class="bi bi-check-circle-fill"></i> বিষাক্ত চর্মরোগ দূর করবে</li><li><i class="bi bi-check-circle-fill"></i> খোস পাচড়া বা চুলকানি দুর করবে</li><li><i class="bi bi-check-circle-fill"></i> ফাঙ্গাস ও ব্যাকটেরিয়া দুর করবে</li><li><i class="bi bi-check-circle-fill"></i> একজিমা দূর করতে</li><li><i class="bi bi-check-circle-fill"></i> দুই রানের ভাজের পুরাতন দাউদ চিরতরে দুর করবে</li></ul></div><div class="col-md-6"><ul class="benefit-list"><li><i class="bi bi-check-circle-fill"></i> শরীরের কিছু অংশ চাকা চাকা হয়ে</li><li><i class="bi bi-check-circle-fill"></i> যাওয়া বা ফুলে যাওয়া, ফোস্কা পড়া ও</li><li><i class="bi bi-check-circle-fill"></i> চামড়া ঝরে যাওয়া থেকে মুক্তি পাবেন</li><li><i class="bi bi-check-circle-fill"></i> কোমরের নিচে চাকা চাকা দাউদ</li><li><i class="bi bi-check-circle-fill"></i> ইনফেকশন দুর করবে</li><li><i class="bi bi-check-circle-fill"></i> চামড়ায় চুলকানি, র‍্যাশ বা ফুসকুড়ি দুর করবেন</li></ul></div></div></div></section><div class="text-center"><button class="btn-order">অর্ডার করুন 🛒</button></div><div class="greenbox text-center"><p class="offer-description1 mx-auto">
        কি কি উপাধান দিয়ে তৈরি আমাদের এলার্জি নিষ্কাশন,এবং চর্মরোগ অয়েল
      </p></div><section class="offer-extended text-center py-5 bg-light"><div class="container"><img src="/storage/images/allergy-cure/3-2-1024x1024.jpg" alt="Chormorog Tel" class="img-fluid mb-4 offer-image"/></div></section><section class="bg-light py-5 text-center"><div class="container"><div class="row text-start justify-content-center"><div class="col-md-6"><ul class="ingredient-list"><li><i class="bi bi-check-circle-fill"></i> নিম পাতা</li><li><i class="bi bi-check-circle-fill"></i> বহেড়া পাতা</li><li><i class="bi bi-check-circle-fill"></i> ভাঁট পাতা</li><li><i class="bi bi-check-circle-fill"></i> ইউক্যালিপটাস পাতা</li><li><i class="bi bi-check-circle-fill"></i> ইউক্বার</li><li><i class="bi bi-check-circle-fill"></i> আতু হায়াসি</li><li><i class="bi bi-check-circle-fill"></i> গ্রীফলা</li></ul></div><div class="col-md-6"><ul class="ingredient-list"><li><i class="bi bi-check-circle-fill"></i> থানকুনি পাতা</li><li><i class="bi bi-check-circle-fill"></i> পুদিনা পাতা</li><li><i class="bi bi-check-circle-fill"></i> জিলুক পাতা</li><li><i class="bi bi-check-circle-fill"></i> আদার মনি</li><li><i class="bi bi-check-circle-fill"></i> তিতাকুল লতা</li><li><i class="bi bi-check-circle-fill"></i> থানি ভল্লানি</li><li><i class="bi bi-check-circle-fill"></i> খুরকরি</li><li><i class="bi bi-check-circle-fill"></i> মামানানি ও ফুলাবেরসি</li></ul></div></div><!-- Note about more ingredients --><p class="mt-4 fw-bold">
            আরও ১৮ টি উপাদান দিয়ে তৈরি মোট ৩৩ টি শক্তিশালী প্রাকৃতিক নির্যাস দিয়ে তৈরি আমাদের এলার্জি নিষ্কাশন এবং চর্মরোগ অয়েল।
          </p><!-- Green CTA Box --><div class="green-box my-4 mx-auto">
            👉 আমাদের এলার্জি নিষ্কাশন এবং চর্মরোগ অয়েল ব্যবহার কোন সাইডইফেক্ট এবং কেমিক্যাল মুক্ত। কোনো সাইডইফেক্ট নেই।
          </div><!-- Section Footer Heading --><div class="green-footer text-white fw-bold py-3">
            এলার্জি নিষ্কাশন খাওয়ার নিয়মঃ
          </div></div></section><section class="bg-light py-5 text-center"><div class="container"><div class="row align-items-center justify-content-center"><div class="col-md-5"><img src="/storage/images/allergy-cure/4-2-1024x1024 (1).jpg" alt="চর্মরোগ তেল" class="img-fluid rounded shadow-sm mb-4"/></div><div class="col-md-6 text-center"><p class="fw-bold fs-5">
                প্রতিদিন সকাল, এবং রাত খাওয়া আগে ১টা চামচ পাউডার নিয়ে,, হালকা গরম পানির মধ্যে ডিজল্ভ ভালো করে মিশ্রণ করে খেয়ে নিবেন,, 👉 অথবা ঠান্ডা পানির মধ্যে ২০মিনিট রেখে ভালো করে মিশ্রণ করে খেয়ে নিবেন।
              </p><a href="#" class="btn btn-order mt-3">অর্ডার করুন 🛒</a></div></div></div></section><!-- Green Heading Between --><section class="text-center py-3 bg-green text-white"><h5 class="fw-bold mb-0">চর্মরোগ অয়েল ব্যবহারের নিয়মঃ</h5></section><!-- এলার্জি নিষ্কাশন --><section class="bg-light py-5 text-center"><div class="container"><div class="row align-items-center justify-content-center"><div class="col-md-5"><img src="/storage/images/allergy-cure/4-2-1024x1024.jpg" alt="এলার্জি নিষ্কাশন" class="img-fluid rounded shadow-sm mb-4"/></div><div class="col-md-6 text-center"><p class="fw-bold fs-5">
                প্রতিদিন রাতে এবং সকালে একটি বাটির মধ্যে তেলটি ৭ থেকে ৮ ফুটা ওয়েল নিবেন এবং অল্প পরিমাণে হলুদ নিবেন এবং ১ ফোঁটা নারিকেল তেল নিবেন তার পর তিনটি আইটেমকে ভালো করে মিশ্রণ করবেন তার পরে আপনার চর্মরোগ বা এলার্জির আক্রান্ত স্থানে ব্যবহার করবেন ইনশাআল্লাহ। ৫ দিনের মধ্যে ফল পাবেন।
              </p><a href="#" class="btn btn-order mt-3">অর্ডার করুন 🛒</a></div></div></div></section><section class="bg-light py-5 text-center"><div class="container"><p class="refund-text mx-auto mb-4">
            প্রিয় ভাই, আমাদের প্রোডাক্ট কেনার পর যদি সম্পূর্ণ ব্যবহার করে ও যদি কাজ না,, করে,,, তাহলে,,, আমাকে এই নাম্বারে একটা কল দিবেন 01819000000 এবং বলবেন, ভাই , আপনার কাছ থেকে যে প্রোডাক্ট নিছিলাম, আমি সেটা সম্পূর্ণ ব্যবহার করেছি কিন্তু একটুও রেজাল্ট এবং কোন উপকার পাচ্ছি না এবং আমার এলার্জি এবং চর্মরোগ কিছুই কমছে না,,,, তখন আমি,,, আপনার বাড়িতে আমাদের ডেলিভারি ম্যান কে পাঠিয়ে দিবো, তখন,, থাক,, আপনার ব্যবহার করা প্রোডাক্টটি ফেরত দিবেন,, এবং সে আপনার ফুল টাকা রিটার্ন দিবে, 👉আমাদের প্রোডাক্ট কেনার সাথে সাথে যতদিন পর্যন্ত না আপনার চর্মরোগ এবং এলার্জি না কমছে ততদিন পর্যন্ত আপনাকে আমি দিকনির্দেশনা এবং গাইড দিয়ে থাকবো ইনশাআল্লাহ। আমাদের উপর পূর্ণ আস্থা রাখুন নিরাশ হবেন না ১০০% ফলাফল পাবেন ইনশাআল্লাহ
          </p><h4 class="fw-bold text-black">আর যদি শুধু এলার্জি নিষ্কাশন অথবা চর্মরোগ অয়েল নিতে চান নিতে পারেন</h4></div></section><section class="bg-light py-5 text-center"><div class="container"><div class="row justify-content-center g-4"><!-- Card 1 --><div class="col-md-6 col-lg-5"><div class="card h-100 shadow-sm border-orange"><img src="/storage/images/allergy-cure/3-2-1024x1024.jpg" alt="এলার্জি নিষ্কাশন" class="card-img-top"/><div class="card-body"><h5 class="card-title fw-bold">এলার্জি নিষ্কাশন</h5><a href="#" class="btn btn-order mt-3">অর্ডার করুন 🛒</a></div></div></div><!-- Card 2 --><div class="col-md-6 col-lg-5"><div class="card h-100 shadow-sm border-orange"><img src="/storage/images/allergy-cure/4-2-1024x1024.jpg" alt="চর্মরোগ অয়েল" class="card-img-top"/><div class="card-body"><h5 class="card-title fw-bold">চর্মরোগ অয়েল</h5><a href="#" class="btn btn-order mt-3">অর্ডার করুন 🛒</a></div></div></div></div></div></section></div></body>
